simulator_url: "http://localhost:8080"
refresh_rate_ms: 250

main_doors:
  - "0,60,0"
  - "0,60,1"

windows:
  1:
    room_id: 1
    coords:
      - "25,64,0"
      - "26,64,0"

light_groups:
  1:
    device_id: 1
    use_active_block: REDSTONE_BLOCK
    use_unactive_block: COBBLESTONE
    activator_button: "12,64,-10"
    activation_coords:
      - "10,60,0"
      - "10,60,1"
