main: com.nacdlow.minecraftsim.Main
name: NacdlowMinecraftSimulation
author: Nacdlow
api-version: 1.15
version: 0.1

commands:
  sim:
    description: Nacdlow's Minecraft Simulation status command
    usage: /sim
